/* The following code was generated by JFlex 1.6.1 */

package ranttu.rapid.jexp.compile.jflex;

import ranttu.rapid.jexp.compile.parse.Token;
import ranttu.rapid.jexp.compile.parse.TokenType;

/**
 * ### WARNING ###
 * this file is generated by src/jflex/jexp.flex, don't modify this directly
 *
 * the lexer generated by jflex
 * @author rapidhere@gmail.com
 */
@SuppressWarnings("all")

public class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING_DOUBLE_QUOTE = 2;
  public static final int STRING_SINGLE_QUOTE = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\2\1\1\1\0\1\2\1\1\22\0\1\2\1\55\1\61"+
    "\2\0\1\12\1\17\1\62\1\13\1\23\1\10\1\6\1\24\1\7"+
    "\1\25\1\11\1\3\11\4\1\57\1\0\1\56\1\30\1\31\2\0"+
    "\27\60\1\5\2\60\1\26\1\63\1\27\1\0\1\60\1\0\1\20"+
    "\1\46\1\42\1\22\1\40\1\34\1\50\1\45\1\36\1\51\1\60"+
    "\1\41\1\35\1\21\1\15\1\54\1\52\1\16\1\37\1\43\1\53"+
    "\1\60\1\44\1\5\1\47\1\60\1\32\1\14\1\33\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uff92\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\1\2\2\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\1\1\4\1\1\2\4\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\12\4\1\24\1\25\1\26\1\27\1\30\1\31\1\32"+
    "\1\33\1\31\1\33\1\34\2\0\2\35\1\36\1\37"+
    "\3\4\1\40\1\41\1\42\2\4\1\43\5\4\1\44"+
    "\2\4\1\45\1\46\1\47\1\50\1\51\1\52\1\53"+
    "\1\4\1\37\7\4\1\54\7\4\1\55\1\4\1\56"+
    "\2\4\1\57\2\4\1\60\3\4\1\61\2\4\1\62"+
    "\1\63\3\4\1\64\1\65\1\66\4\4\1\67\1\4"+
    "\1\70";

  private static int [] zzUnpackAction() {
    int [] result = new int[126];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\64\0\150\0\234\0\234\0\320\0\u0104\0\u0138"+
    "\0\234\0\234\0\234\0\234\0\234\0\234\0\u016c\0\u01a0"+
    "\0\u01d4\0\u0208\0\u023c\0\234\0\234\0\234\0\234\0\234"+
    "\0\u0270\0\u02a4\0\234\0\234\0\u02d8\0\u030c\0\u0340\0\u0374"+
    "\0\u03a8\0\u03dc\0\u0410\0\u0444\0\u0478\0\u04ac\0\u04e0\0\u0514"+
    "\0\234\0\234\0\234\0\u0548\0\234\0\u057c\0\u05b0\0\u05e4"+
    "\0\u0618\0\u064c\0\u0680\0\234\0\u06b4\0\u0138\0\234\0\u06e8"+
    "\0\u071c\0\u0750\0\234\0\234\0\234\0\u0784\0\u07b8\0\u07ec"+
    "\0\u0820\0\u0854\0\u0888\0\u08bc\0\u08f0\0\u0138\0\u0924\0\u0958"+
    "\0\234\0\234\0\234\0\234\0\234\0\u064c\0\u0680\0\u098c"+
    "\0\u0138\0\u09c0\0\u09f4\0\u0a28\0\u0a5c\0\u0a90\0\u0ac4\0\u0af8"+
    "\0\u0138\0\u0b2c\0\u0b60\0\u0b94\0\u0bc8\0\u0bfc\0\u0c30\0\u0c64"+
    "\0\u0138\0\u0c98\0\u0138\0\u0ccc\0\u0d00\0\u0138\0\u0d34\0\u0d68"+
    "\0\u0138\0\u0d9c\0\u0dd0\0\u0e04\0\u0138\0\u0e38\0\u0e6c\0\u0138"+
    "\0\u0138\0\u0ea0\0\u0ed4\0\u0f08\0\u0138\0\u0138\0\u0138\0\u0f3c"+
    "\0\u0f70\0\u0fa4\0\u0fd8\0\u0138\0\u100c\0\u0138";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[126];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\2\4\1\5\1\6\1\7\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\10\1\21\1\22"+
    "\1\10\1\23\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\1\34\1\35\1\10\1\36\1\37\1\40"+
    "\1\41\1\10\1\42\1\43\1\10\1\44\1\10\1\45"+
    "\1\46\3\10\1\47\1\50\1\51\1\10\1\52\1\53"+
    "\1\4\1\54\1\4\57\54\1\55\1\54\1\56\1\57"+
    "\1\4\60\57\1\55\1\60\67\0\2\61\1\62\17\0"+
    "\1\63\41\0\2\7\20\0\1\63\41\0\3\10\7\0"+
    "\2\10\1\0\3\10\11\0\21\10\3\0\1\10\17\0"+
    "\1\64\52\0\3\10\7\0\1\10\1\65\1\0\1\10"+
    "\1\66\1\10\11\0\21\10\3\0\1\10\22\0\1\67"+
    "\47\0\3\10\7\0\2\10\1\0\1\10\1\70\1\10"+
    "\11\0\3\10\1\71\15\10\3\0\1\10\6\0\3\10"+
    "\7\0\2\10\1\0\3\10\11\0\4\10\1\72\14\10"+
    "\3\0\1\10\33\0\1\73\1\74\62\0\1\75\36\0"+
    "\3\10\7\0\1\10\1\76\1\0\1\77\2\10\11\0"+
    "\21\10\3\0\1\10\6\0\3\10\7\0\2\10\1\0"+
    "\1\10\1\100\1\10\11\0\21\10\3\0\1\10\6\0"+
    "\3\10\7\0\2\10\1\0\3\10\11\0\4\10\1\101"+
    "\14\10\3\0\1\10\6\0\3\10\7\0\2\10\1\0"+
    "\3\10\11\0\16\10\1\102\2\10\3\0\1\10\6\0"+
    "\3\10\7\0\2\10\1\0\3\10\11\0\4\10\1\103"+
    "\14\10\3\0\1\10\6\0\3\10\7\0\1\10\1\104"+
    "\1\0\3\10\11\0\21\10\3\0\1\10\6\0\3\10"+
    "\7\0\2\10\1\0\3\10\11\0\11\10\1\105\7\10"+
    "\3\0\1\10\6\0\3\10\7\0\2\10\1\0\3\10"+
    "\11\0\13\10\1\106\5\10\3\0\1\10\6\0\3\10"+
    "\7\0\1\10\1\107\1\0\3\10\11\0\21\10\3\0"+
    "\1\10\6\0\3\10\7\0\1\110\1\10\1\0\3\10"+
    "\11\0\21\10\3\0\1\10\33\0\1\111\63\0\1\112"+
    "\33\0\1\54\1\0\57\54\1\0\1\54\44\0\1\113"+
    "\15\0\1\114\2\0\1\57\1\0\60\57\45\0\1\113"+
    "\16\0\1\115\4\0\2\61\62\0\2\116\62\0\2\117"+
    "\62\0\3\10\7\0\2\10\1\0\2\10\1\120\11\0"+
    "\21\10\3\0\1\10\6\0\3\10\7\0\2\10\1\0"+
    "\2\10\1\121\11\0\21\10\3\0\1\10\6\0\3\10"+
    "\7\0\2\10\1\0\3\10\11\0\6\10\1\122\12\10"+
    "\3\0\1\10\6\0\3\10\7\0\2\10\1\0\3\10"+
    "\11\0\3\10\1\123\15\10\3\0\1\10\6\0\3\10"+
    "\7\0\1\124\1\10\1\0\3\10\11\0\21\10\3\0"+
    "\1\10\6\0\3\10\7\0\2\10\1\0\3\10\11\0"+
    "\5\10\1\125\13\10\3\0\1\10\6\0\3\10\7\0"+
    "\2\10\1\0\3\10\11\0\7\10\1\126\11\10\3\0"+
    "\1\10\6\0\3\10\7\0\2\10\1\0\3\10\11\0"+
    "\5\10\1\127\13\10\3\0\1\10\6\0\3\10\7\0"+
    "\2\10\1\0\3\10\11\0\17\10\1\130\1\10\3\0"+
    "\1\10\6\0\3\10\7\0\2\10\1\0\3\10\11\0"+
    "\7\10\1\131\11\10\3\0\1\10\6\0\3\10\7\0"+
    "\2\10\1\0\3\10\11\0\17\10\1\132\1\10\3\0"+
    "\1\10\6\0\3\10\7\0\2\10\1\0\3\10\11\0"+
    "\4\10\1\133\14\10\3\0\1\10\6\0\3\10\7\0"+
    "\1\134\1\10\1\0\3\10\11\0\21\10\3\0\1\10"+
    "\6\0\3\10\7\0\2\10\1\0\3\10\11\0\2\10"+
    "\1\135\16\10\3\0\1\10\6\0\3\10\7\0\2\10"+
    "\1\0\3\10\11\0\4\10\1\136\14\10\3\0\1\10"+
    "\6\0\3\10\7\0\2\10\1\0\3\10\11\0\4\10"+
    "\1\137\14\10\3\0\1\10\6\0\3\10\7\0\2\10"+
    "\1\0\3\10\11\0\6\10\1\140\12\10\3\0\1\10"+
    "\6\0\3\10\7\0\2\10\1\0\3\10\11\0\1\10"+
    "\1\141\17\10\3\0\1\10\6\0\3\10\7\0\2\10"+
    "\1\0\3\10\11\0\3\10\1\142\15\10\3\0\1\10"+
    "\6\0\3\10\7\0\1\143\1\10\1\0\3\10\11\0"+
    "\21\10\3\0\1\10\6\0\3\10\7\0\2\10\1\0"+
    "\3\10\11\0\4\10\1\144\14\10\3\0\1\10\6\0"+
    "\3\10\7\0\2\10\1\0\1\145\2\10\11\0\21\10"+
    "\3\0\1\10\6\0\3\10\7\0\2\10\1\0\3\10"+
    "\11\0\4\10\1\146\14\10\3\0\1\10\6\0\3\10"+
    "\7\0\1\10\1\147\1\0\3\10\11\0\21\10\3\0"+
    "\1\10\6\0\3\10\7\0\2\10\1\0\3\10\11\0"+
    "\17\10\1\150\1\10\3\0\1\10\6\0\3\10\7\0"+
    "\2\10\1\0\1\10\1\151\1\10\11\0\21\10\3\0"+
    "\1\10\6\0\3\10\7\0\1\10\1\152\1\0\3\10"+
    "\11\0\21\10\3\0\1\10\6\0\3\10\7\0\2\10"+
    "\1\0\1\10\1\153\1\10\11\0\21\10\3\0\1\10"+
    "\6\0\3\10\7\0\2\10\1\0\3\10\11\0\4\10"+
    "\1\154\14\10\3\0\1\10\6\0\3\10\7\0\2\10"+
    "\1\0\3\10\11\0\4\10\1\155\14\10\3\0\1\10"+
    "\6\0\3\10\7\0\2\10\1\0\3\10\11\0\6\10"+
    "\1\156\12\10\3\0\1\10\6\0\3\10\7\0\2\10"+
    "\1\0\3\10\11\0\5\10\1\157\13\10\3\0\1\10"+
    "\6\0\3\10\7\0\2\10\1\0\3\10\11\0\4\10"+
    "\1\160\14\10\3\0\1\10\6\0\3\10\7\0\2\10"+
    "\1\0\3\10\11\0\20\10\1\161\3\0\1\10\6\0"+
    "\3\10\7\0\2\10\1\0\3\10\11\0\12\10\1\162"+
    "\6\10\3\0\1\10\6\0\3\10\7\0\2\10\1\0"+
    "\2\10\1\163\11\0\21\10\3\0\1\10\6\0\3\10"+
    "\7\0\2\10\1\0\1\10\1\164\1\10\11\0\21\10"+
    "\3\0\1\10\6\0\3\10\7\0\2\10\1\0\3\10"+
    "\11\0\7\10\1\165\11\10\3\0\1\10\6\0\3\10"+
    "\7\0\2\10\1\0\3\10\11\0\3\10\1\166\15\10"+
    "\3\0\1\10\6\0\3\10\7\0\2\10\1\0\3\10"+
    "\11\0\13\10\1\167\5\10\3\0\1\10\6\0\3\10"+
    "\7\0\2\10\1\0\3\10\11\0\2\10\1\170\16\10"+
    "\3\0\1\10\6\0\3\10\7\0\2\10\1\0\2\10"+
    "\1\171\11\0\21\10\3\0\1\10\6\0\3\10\7\0"+
    "\2\10\1\0\1\10\1\172\1\10\11\0\21\10\3\0"+
    "\1\10\6\0\3\10\7\0\2\10\1\0\3\10\11\0"+
    "\2\10\1\173\16\10\3\0\1\10\6\0\3\10\7\0"+
    "\2\10\1\0\3\10\11\0\14\10\1\174\4\10\3\0"+
    "\1\10\6\0\3\10\7\0\2\10\1\0\1\10\1\175"+
    "\1\10\11\0\21\10\3\0\1\10\6\0\3\10\7\0"+
    "\2\10\1\0\3\10\11\0\14\10\1\176\4\10\3\0"+
    "\1\10\3\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4160];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\2\11\3\1\6\11\5\1\5\11\2\1\2\11"+
    "\14\1\3\11\1\1\1\11\4\1\2\0\1\11\2\1"+
    "\1\11\3\1\3\11\13\1\5\11\61\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[126];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
  private StringBuffer string = new StringBuffer();

  private Token token(TokenType type, Object val) {
      return new Token(type, yyline, yycolumn, val);
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 170) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { throw new Error("unexpected character at line "
                                            + yyline + ", column " + yycolumn + ": " + yytext());
            }
          case 57: break;
          case 2: 
            { /* ignore */
            }
          case 58: break;
          case 3: 
            { return token(TokenType.INTEGER, Integer.valueOf(yytext()));
            }
          case 59: break;
          case 4: 
            { return token(TokenType.IDENTIFIER, yytext());
            }
          case 60: break;
          case 5: 
            { return token(TokenType.PLUS, yytext());
            }
          case 61: break;
          case 6: 
            { return token(TokenType.SUBTRACT, yytext());
            }
          case 62: break;
          case 7: 
            { return token(TokenType.MULTIPLY, yytext());
            }
          case 63: break;
          case 8: 
            { return token(TokenType.DIVIDE, yytext());
            }
          case 64: break;
          case 9: 
            { return token(TokenType.MODULAR, yytext());
            }
          case 65: break;
          case 10: 
            { return token(TokenType.LEFT_PARENTHESIS, yytext());
            }
          case 66: break;
          case 11: 
            { return token(TokenType.RIGHT_PARENTHESIS, yytext());
            }
          case 67: break;
          case 12: 
            { return token(TokenType.COMMA, yytext());
            }
          case 68: break;
          case 13: 
            { return token(TokenType.DOT, yytext());
            }
          case 69: break;
          case 14: 
            { return token(TokenType.LEFT_BRACKET, yytext());
            }
          case 70: break;
          case 15: 
            { return token(TokenType.RIGHT_BRACKET, yytext());
            }
          case 71: break;
          case 16: 
            { return token(TokenType.EQ, yytext());
            }
          case 72: break;
          case 17: 
            { return token(TokenType.GREATER, yytext());
            }
          case 73: break;
          case 18: 
            { return token(TokenType.LEFT_BRACE, yytext());
            }
          case 74: break;
          case 19: 
            { return token(TokenType.RIGHT_BRACE, yytext());
            }
          case 75: break;
          case 20: 
            { return token(TokenType.NOT, yytext());
            }
          case 76: break;
          case 21: 
            { return token(TokenType.SMALLER, yytext());
            }
          case 77: break;
          case 22: 
            { return token(TokenType.SEMI_COLON, yytext());
            }
          case 78: break;
          case 23: 
            { string.setLength(0); yybegin(STRING_DOUBLE_QUOTE);
            }
          case 79: break;
          case 24: 
            { string.setLength(0); yybegin(STRING_SINGLE_QUOTE);
            }
          case 80: break;
          case 25: 
            { string.append( yytext() );
            }
          case 81: break;
          case 26: 
            { yybegin(YYINITIAL);
                                   return token(TokenType.STRING, string.toString());
            }
          case 82: break;
          case 27: 
            { string.append('\\');
            }
          case 83: break;
          case 28: 
            { return token(TokenType.INTEGER, Integer.parseInt(yytext(), 8));
            }
          case 84: break;
          case 29: 
            { return token(TokenType.OR, yytext());
            }
          case 85: break;
          case 30: 
            { return token(TokenType.ON, yytext());
            }
          case 86: break;
          case 31: 
            { return token(TokenType.AND, yytext());
            }
          case 87: break;
          case 32: 
            { return token(TokenType.EQEQ, yytext());
            }
          case 88: break;
          case 33: 
            { return token(TokenType.POINTER, yytext());
            }
          case 89: break;
          case 34: 
            { return token(TokenType.GREATER_EQ, yytext());
            }
          case 90: break;
          case 35: 
            { return token(TokenType.IN, yytext());
            }
          case 91: break;
          case 36: 
            { return token(TokenType.BY, yytext());
            }
          case 92: break;
          case 37: 
            { return token(TokenType.NOT_EQ, yytext());
            }
          case 93: break;
          case 38: 
            { return token(TokenType.SMALLER_EQ, yytext());
            }
          case 94: break;
          case 39: 
            { string.append('\t');
            }
          case 95: break;
          case 40: 
            { string.append('\"');
            }
          case 96: break;
          case 41: 
            { string.append('\'');
            }
          case 97: break;
          case 42: 
            { return token(TokenType.INTEGER, Integer.parseInt(yytext().substring(2), 16));
            }
          case 98: break;
          case 43: 
            { return token(TokenType.FLOAT, Double.valueOf(yytext()));
            }
          case 99: break;
          case 44: 
            { return token(TokenType.LET, yytext());
            }
          case 100: break;
          case 45: 
            { return token(TokenType.FROM, yytext());
            }
          case 101: break;
          case 46: 
            { return token(TokenType.INTO, yytext());
            }
          case 102: break;
          case 47: 
            { return token(TokenType.TRUE, yytext());
            }
          case 103: break;
          case 48: 
            { return token(TokenType.JOIN, yytext());
            }
          case 104: break;
          case 49: 
            { return token(TokenType.FALSE, yytext());
            }
          case 105: break;
          case 50: 
            { return token(TokenType.WHERE, yytext());
            }
          case 106: break;
          case 51: 
            { return token(TokenType.GROUP, yytext());
            }
          case 107: break;
          case 52: 
            { return token(TokenType.SELECT, yytext());
            }
          case 108: break;
          case 53: 
            { return token(TokenType.EQUALS, yytext());
            }
          case 109: break;
          case 54: 
            { return token(TokenType.ORDERBY, yytext());
            }
          case 110: break;
          case 55: 
            { return token(TokenType.ASCENDING, yytext());
            }
          case 111: break;
          case 56: 
            { return token(TokenType.DESCENDING, yytext());
            }
          case 112: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
